-- MySQL Script generated by MySQL Workbench
-- Mon Mar 31 22:08:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuarios` (
  `id_tipo_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_usuario` VARCHAR(45) NOT NULL,
  `desc_tipo_usuario` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_tipo_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NULL DEFAULT 0,
  `user_id` INT NULL,
  `id_tipo_usuarios` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_tipo_usuarios_idx` (`id_tipo_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuarios`
    FOREIGN KEY (`id_tipo_usuarios`)
    REFERENCES `mydb`.`tipo_usuarios` (`id_tipo_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ubicaciones` (
  `id_ubicaciones` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_ubicaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aeropuertos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aeropuertos` (
  `id_aeropuertos` INT NOT NULL AUTO_INCREMENT,
  `nombre_aeropuerto` VARCHAR(45) NOT NULL,
  `codigo_iata` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  `id_ubicaciones` INT NOT NULL,
  PRIMARY KEY (`id_aeropuertos`),
  UNIQUE INDEX `codigo_iata_UNIQUE` (`codigo_iata` ASC) VISIBLE,
  INDEX `fk_aeropuertos_ubicaciones1_idx` (`id_ubicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_aeropuertos_ubicaciones1`
    FOREIGN KEY (`id_ubicaciones`)
    REFERENCES `mydb`.`ubicaciones` (`id_ubicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vuelos` (
  `id_vuelos` INT NOT NULL AUTO_INCREMENT,
  `numero_vuelo` VARCHAR(45) NOT NULL,
  `aerolinea` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_origen` INT NOT NULL,
  `id_destino` INT NOT NULL,
  PRIMARY KEY (`id_vuelos`),
  UNIQUE INDEX `numero_vuelo_UNIQUE` (`numero_vuelo` ASC) VISIBLE,
  INDEX `fk_vuelos_aeropuertos1_idx` (`id_origen` ASC) VISIBLE,
  INDEX `fk_vuelos_aeropuertos2_idx` (`id_destino` ASC) VISIBLE,
  CONSTRAINT `fk_vuelos_aeropuertos1`
    FOREIGN KEY (`id_origen`)
    REFERENCES `mydb`.`aeropuertos` (`id_aeropuertos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelos_aeropuertos2`
    FOREIGN KEY (`id_destino`)
    REFERENCES `mydb`.`aeropuertos` (`id_aeropuertos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_reserva` (
  `id_estado_reserva` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_estado_reserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `id_reservas` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_reserva` DATETIME NOT NULL,
  `costo_total` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  `user_id` INT NOT NULL,
  `id_estado_reserva` INT NOT NULL,
  PRIMARY KEY (`id_reservas`),
  INDEX `fk_reservas_usuarios1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_reservas_estado_reserva1_idx` (`id_estado_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_usuarios1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`usuarios` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_estado_reserva1`
    FOREIGN KEY (`id_estado_reserva`)
    REFERENCES `mydb`.`estado_reserva` (`id_estado_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_asiento` (
  `id_estado_asiento` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_estado_asiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clase_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clase_asiento` (
  `id_clase_asiento` INT NOT NULL AUTO_INCREMENT,
  `tipo_clase` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_clase_asiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asientos` (
  `id_asientos` INT NOT NULL AUTO_INCREMENT,
  `numero_asiento` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  `reservas_id_reservas` INT NOT NULL,
  `id_estado_asiento` INT NOT NULL,
  `id_clase_asiento` INT NOT NULL,
  PRIMARY KEY (`id_asientos`),
  INDEX `fk_asientos_reservas1_idx` (`reservas_id_reservas` ASC) VISIBLE,
  INDEX `fk_asientos_estado_asiento1_idx` (`id_estado_asiento` ASC) VISIBLE,
  INDEX `fk_asientos_clase_asiento1_idx` (`id_clase_asiento` ASC) VISIBLE,
  CONSTRAINT `fk_asientos_reservas1`
    FOREIGN KEY (`reservas_id_reservas`)
    REFERENCES `mydb`.`reservas` (`id_reservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asientos_estado_asiento1`
    FOREIGN KEY (`id_estado_asiento`)
    REFERENCES `mydb`.`estado_asiento` (`id_estado_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asientos_clase_asiento1`
    FOREIGN KEY (`id_clase_asiento`)
    REFERENCES `mydb`.`clase_asiento` (`id_clase_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vuelos_programados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vuelos_programados` (
  `id_vuelos_programados` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_salida` DATETIME NOT NULL,
  `fecha_hora_llegada` DATETIME NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  `id_vuelos` INT NOT NULL,
  PRIMARY KEY (`id_vuelos_programados`),
  INDEX `fk_vuelos_programados_vuelos1_idx` (`id_vuelos` ASC) VISIBLE,
  CONSTRAINT `fk_vuelos_programados_vuelos1`
    FOREIGN KEY (`id_vuelos`)
    REFERENCES `mydb`.`vuelos` (`id_vuelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VuelosReservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VuelosReservas` (
  `id_vuelos_reservas` INT NOT NULL AUTO_INCREMENT,
  `id_vuelos_programados` INT NOT NULL,
  `reservas_id_reservas` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_vuelos_reservas`, `id_vuelos_programados`, `reservas_id_reservas`),
  INDEX `fk_vuelos_programados_has_reservas_reservas1_idx` (`reservas_id_reservas` ASC) VISIBLE,
  INDEX `fk_vuelos_programados_has_reservas_vuelos_programados1_idx` (`id_vuelos_programados` ASC) VISIBLE,
  CONSTRAINT `fk_vuelos_programados_has_reservas_vuelos_programados1`
    FOREIGN KEY (`id_vuelos_programados`)
    REFERENCES `mydb`.`vuelos_programados` (`id_vuelos_programados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelos_programados_has_reservas_reservas1`
    FOREIGN KEY (`reservas_id_reservas`)
    REFERENCES `mydb`.`reservas` (`id_reservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escalas` (
  `id_escala` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_llegada` DATETIME NOT NULL,
  `fecha_hora_salida` DATETIME NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `user_id` INT NULL,
  `id_aeropuertos` INT NOT NULL,
  PRIMARY KEY (`id_escala`),
  INDEX `fk_escalas_aeropuertos1_idx` (`id_aeropuertos` ASC) VISIBLE,
  CONSTRAINT `fk_escalas_aeropuertos1`
    FOREIGN KEY (`id_aeropuertos`)
    REFERENCES `mydb`.`aeropuertos` (`id_aeropuertos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
