-- MySQL Script generated by MySQL Workbench
-- Mon Mar 24 15:01:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoUsuarios` (
  `id_TipoUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_usuario` VARCHAR(45) NOT NULL,
  `desc_tipo_usuario` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id_TipoUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usarios` (
  `id_Usarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `TipoUsuarios_id_TipoUsuarios` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id_Usarios`),
  INDEX `fk_Usarios_TipoUsuarios_idx` (`TipoUsuarios_id_TipoUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Usarios_TipoUsuarios`
    FOREIGN KEY (`TipoUsuarios_id_TipoUsuarios`)
    REFERENCES `mydb`.`TipoUsuarios` (`id_TipoUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `id_Categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  `desc_producto` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id_Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proovedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proovedor` (
  `id_Proovedor` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `rut_prooverdor` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id_Proovedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `id_Producto` INT NOT NULL AUTO_INCREMENT,
  `Usarios_id_Usarios` INT NOT NULL,
  `Categoria_id_Categoria` INT NOT NULL,
  `Proovedor_id_Proovedor` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `stock` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id_Producto`),
  INDEX `fk_Producto_Usarios1_idx` (`Usarios_id_Usarios` ASC) VISIBLE,
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_id_Categoria` ASC) VISIBLE,
  INDEX `fk_Producto_Proovedor1_idx` (`Proovedor_id_Proovedor` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Usarios1`
    FOREIGN KEY (`Usarios_id_Usarios`)
    REFERENCES `mydb`.`Usarios` (`id_Usarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_id_Categoria`)
    REFERENCES `mydb`.`Categoria` (`id_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Proovedor1`
    FOREIGN KEY (`Proovedor_id_Proovedor`)
    REFERENCES `mydb`.`Proovedor` (`id_Proovedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Promocion` (
  `id_Promocion` INT NOT NULL AUTO_INCREMENT,
  `nombre_promocion` VARCHAR(45) NOT NULL,
  `descuento` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id_Promocion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `metodo_pago` VARCHAR(45) NOT NULL,
  `monto_pagado` VARCHAR(45) NOT NULL,
  `fecha_pago` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Despacho` (
  `id_Despacho` INT NOT NULL AUTO_INCREMENT,
  `direccion_entrega` VARCHAR(45) NOT NULL,
  `fecha_envio` DATE NOT NULL,
  `transportista` VARCHAR(45) NOT NULL,
  `estado_despacho` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id_Despacho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `id_Pedido` INT NOT NULL AUTO_INCREMENT,
  `Pago_idPago` INT NOT NULL,
  `Despacho_id_Despacho` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id_Pedido`),
  INDEX `fk_Pedido_Pago1_idx` (`Pago_idPago` ASC) VISIBLE,
  INDEX `fk_Pedido_Despacho1_idx` (`Despacho_id_Despacho` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Pago1`
    FOREIGN KEY (`Pago_idPago`)
    REFERENCES `mydb`.`Pago` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Despacho1`
    FOREIGN KEY (`Despacho_id_Despacho`)
    REFERENCES `mydb`.`Despacho` (`id_Despacho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetallePedido` (
  `Producto_id_Producto` INT NOT NULL,
  `Pedido_id_Pedido` INT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `precop_unitario` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`Producto_id_Producto`, `Pedido_id_Pedido`),
  INDEX `fk_Producto_has_Pedido_Pedido1_idx` (`Pedido_id_Pedido` ASC) VISIBLE,
  INDEX `fk_Producto_has_Pedido_Producto1_idx` (`Producto_id_Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Pedido_Producto1`
    FOREIGN KEY (`Producto_id_Producto`)
    REFERENCES `mydb`.`Producto` (`id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_id_Pedido`)
    REFERENCES `mydb`.`Pedido` (`id_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoPromocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoPromocion` (
  `Producto_id_Producto` INT NOT NULL,
  `Promocion_id_Promocion` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`Producto_id_Producto`, `Promocion_id_Promocion`),
  INDEX `fk_Producto_has_Promocion_Promocion1_idx` (`Promocion_id_Promocion` ASC) VISIBLE,
  INDEX `fk_Producto_has_Promocion_Producto1_idx` (`Producto_id_Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Promocion_Producto1`
    FOREIGN KEY (`Producto_id_Producto`)
    REFERENCES `mydb`.`Producto` (`id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Promocion_Promocion1`
    FOREIGN KEY (`Promocion_id_Promocion`)
    REFERENCES `mydb`.`Promocion` (`id_Promocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reseña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reseña` (
  `id_Reseña` INT NOT NULL AUTO_INCREMENT,
  `Usarios_id_Usarios` INT NOT NULL,
  `Producto_id_Producto` INT NOT NULL,
  `calificacion` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  `fecha_reseña` DATE NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id_Reseña`, `Usarios_id_Usarios`, `Producto_id_Producto`),
  INDEX `fk_Usarios_has_Producto_Producto1_idx` (`Producto_id_Producto` ASC) VISIBLE,
  INDEX `fk_Usarios_has_Producto_Usarios1_idx` (`Usarios_id_Usarios` ASC) VISIBLE,
  CONSTRAINT `fk_Usarios_has_Producto_Usarios1`
    FOREIGN KEY (`Usarios_id_Usarios`)
    REFERENCES `mydb`.`Usarios` (`id_Usarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usarios_has_Producto_Producto1`
    FOREIGN KEY (`Producto_id_Producto`)
    REFERENCES `mydb`.`Producto` (`id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;